language: generic
addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell
script:
  - pwsh ./scripts/findMissingMarkdowns.ps1 -Version 4.0
  - pwsh ./scripts/findMissingMarkdowns.ps1 -Version 4.1
  - pwsh ./scripts/findMissingMarkdowns.ps1 -Version 4.2